# Generated by Django 5.1.1 on 2024-12-10 09:41

from django.db import migrations
from django.utils.text import slugify

# from hottrack.models import Song


def forward_code(apps, schema_editor):
    Song = apps.get_model("hottrack", "Song")
    qs = Song.objects.filter(slug="")
    for song in qs:
        song.slug = slugify(song.name, allow_unicode=True)
    Song.objects.bulk_update(qs, ["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("hottrack", "0002_song_slug_song_hottrack_so_slug_7cf104_idx"),
    ]

    operations = [
        migrations.RunPython(forward_code, reverse_code=migrations.RunPython.noop),
    ]
