# Generated by Django 5.1.1 on 2024-12-19 09:59

import core.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_category_alter_post_author_post_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_generic", models.GenericIPAddressField(protocol="IPv4")),
                ("ip_int", core.model_fields.IPv4AddressIntegerField(max_length=15)),
            ],
        ),
    ]
