# Generated by Django 5.1.1 on 2024-12-19 10:48

import core.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_accesslog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "is_public_ch",
                    models.CharField(
                        choices=[("Y", "예"), ("N", "아니요")],
                        default="N",
                        max_length=1,
                    ),
                ),
                (
                    "is_public_yn",
                    core.model_fields.BooleanYNField(default=False, max_length=1),
                ),
            ],
        ),
    ]
